### ISSUE TITLE
Action not working because of missing js file

### ISSUE THREAD

**Issue by saitho** [cherryblossom000/semantic-release-action-pnpm#1]
**Describe the bug**
Action fails because the JavaScript file is not found.

> File not found: '/home/runner/work/_actions/cherryblossom000/semantic-release-action-pnpm/v1.0.0/dist/index.js'

That's obviously because the repo only contains TypeScript files. :)

**Workflow**
https://github.com/saitho/bingo/blob/master/.github/workflows/nodejs.yml

**Expected behaviour**
Action should work.

**Comment by cherryblossom000** [comment]
Thanks for letting me know! I fixed this in v1.0.1.

I can't believe I actually didn't commit the build result.
